### ISSUE TITLE
Cannot specify more than one scope in New-PartnerAccessToken cmdlet despite it having "scopes"

### ISSUE THREAD

**Issue by cblackuk** [microsoft/Partner-Center-PowerShell#167]
# Steps to reproduce

```powershell
[String[]]$ScopesTest = 'https://api.partnercenter.microsoft.com/user_impersonation'
[String[]]$ScopesTest += 'https://management.azure.com/user_impersonation'

PS C:\Windows\system32> $ScopesTest
https://api.partnercenter.microsoft.com/user_impersonation
https://management.azure.com/user_impersonation

PS C:\Windows\system32> $RefreshTokenForTestingAuthSPNFull = New-PartnerAccessToken -ApplicationId 'xxxxx-xxxx-xxxx-xxxx-xxxx' -Scopes $ScopesTest -ServicePrincipal -Credential $Credentials -Tenant "xxx-xxx-xxx-xxx-xxxxx" -UseAuthorizationCode
WARNING: Attempting to launch a browser for authorization code login.
WARNING: We have launched a browser for you to login. For the old experience with device code flow, please run 'New-PartnerAccessToken -UseDeviceAuthentication'.
New-PartnerAccessToken : AADSTS28000: Provided value for the input parameter scope is not valid because it contains more than one resource. Scope 
https://api.partnercenter.microsoft.com/user_impersonation https://management.azure.com/user_impersonation offline_access openid profile is not valid.
Trace ID: 55a1357c-a6dd-4337-9b9f-473cbbe74200
Correlation ID: def32739-9e85-48fb-a4e2-8248d697d91f
Timestamp: 2019-09-26 11:08:05Z
At line:1 char:38
+ ... thSPNFull = New-PartnerAccessToken -ApplicationId 'xxx-xxx-xxx...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-PartnerAccessToken], MsalServiceException
    + FullyQualifiedErrorId : Microsoft.Identity.Client.MsalServiceException,Microsoft.Store.PartnerCenter.PowerShell.Commands.NewPartnerAccessToken
```

## Expected behavior

Should add scopes to the authorisation but instead the code parses all the strings into the cmd.

```
GET /xxxx-xxx-xxxx-xxxx-xxxxx/oauth2/v2.0/authorize?scope=https:%2F%2Fapi.partnercenter.microsoft.com%2Fuser_impersonation+https:%2F%2Fmanagement.azure.com%2Fuser_impersonation+offline_access+openid+profile&response_type=code&client_id=xxxx-xxxx-xxxx-xxxx-xxxxxxx&redirect_uri=http:%2F%2Flocalhost:8400%2F&client-request-id=558d721e-afa2-4082-a5ac-8b3d8fb74033&x-client-SKU=MSAL.CoreCLR&x-client-Ver=3.0.8.0&prompt=select_account HTTP/1.1
```

Version:
```powershell
PS C:\Windows\system32> Get-Module -Name PartnerCenter

ModuleType Version    Name                                ExportedCommands                                                                                              
---------- -------    ----                                ----------------                                                                                              
Script     2.0.1909.5 PartnerCenter                       {Add-PartnerCustomerCartLineItem, Add-PartnerCustomerUserRoleMember, Connect-PartnerCenter, Disconnect-Part...


```

**Comment by cblackuk** [comment]
```powershell
[String[]]$ScopesTest = "https://graph.windows.net/Directory.Read"
[String[]]$ScopesTest += "https://graph.windows.net/Directory.Write"

PS C:\Users\Administrator> $RefreshTokenForTestingAuthSPNFull = New-PartnerAccessToken -ApplicationId 'xxx-xxx-xxx-xxx-xxxxxx' -Scopes $ScopesTest -ServicePrincipal -Credential $Credentials -Tenant "xxx-xxx-xxx-xxx-xxxxxx" -UseAuthorizationCode
WARNING: Attempting to launch a browser for authorization code login.
WARNING: We have launched a browser for you to login. For the old experience with device code flow, please run 'New-PartnerAccessToken -UseDeviceAuthentication'.
New-PartnerAccessToken : AuthorizationCode can not be null or whitespace
Parameter name: AuthorizationCode
At line:1 char:38
+ ... thSPNFull = New-PartnerAccessToken -ApplicationId 'xxxx-xxxx-xxx...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-PartnerAccessToken], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.Store.PartnerCenter.PowerShell.Commands.NewPartnerAccessToken
```

This should be a better example because it should work as per:

https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-migration#scopes-for-a-web-api-accepting-v10-tokens

![image](https://user-images.githubusercontent.com/28607803/65776773-aab74100-e13a-11e9-9c34-4aaf5e14c5c5.png)

**Comment by cblackuk** [comment]
The return we got from the API is:

```
GET http://localhost:8400/?error=invalid_client&error_description=AADSTS650053%3a+The+application+%27Partner+Center+Web+App%27+asked+for+scope+%27Directory.Read%27+that+doesn%27t+exist+on+the+resource+%2700000003-0000-0000-c000-000000000000%27.+Contact+the+app+vendor.%0d%0aTrace+ID%3a+39311888-5dce-4c7f-9059-9f35cf116400%0d%0aCorrelation+ID%3a+xxx-xxx-xxx-xxx-xxxx%0d%0aTimestamp%3a+2019-09-27+14%3a51%3a23Z HTTP/1.1
Accept: text/html, application/xhtml+xml, image/jxr, */*
Referer: https://login.microsoftonline.com/
Accept-Language: en-GB,en;q=0.5
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko
Accept-Encoding: gzip, deflate
Cache-Control: no-cache
Host: localhost:8400
Connection: Keep-Alive
Pragma: no-cache


```

**Comment by isaiahwilliams** [comment]
@cblackuk with the last example you shared were you using an Azure Active Directory that had the Azure Active Directory Graph permissions assigned correct?

**Comment by cblackuk** [comment]
No, it was more to show that it shows 200 in the "GUI"/Website but the error is just inside the GET - it obviously all failed. Unless you are asking if my SPN has got correct permissions - in which case - yes it does but you still cannot do anything from the cmdlet as shown above.

**Comment by isaiahwilliams** [comment]
@cblackuk my apologizes for not updating this sooner. This particular issue was addressed with the 2.0.1911.1 release. If you are curious you can see what was done [here](https://github.com/microsoft/Partner-Center-PowerShell/blob/master/src/PowerShell/Network/DefaultOsBrowserWebUi.cs). Please let us know if you have any other issues.

**Comment by cblackuk** [comment]
Thanks @isaiahwilliams! I will test it soon :-)

**Comment by slavizh** [comment]
the cmdlet for token still does not accepts more than one scope.
New-PartnerAccessToken : AADSTS28000: Provided value for the input parameter scope is not valid because it contains more than one resource. Scope https://api.partnercenter.microsoft.com/user_impersonation ht
tps://management.azure.com/user_impersonation offline_access openid profile is not valid.

**Comment by cblackuk** [comment]
Sad ;-(

**Comment by aconn21** [comment]
Why is this issue closed? I'm also experiencing the same problem. Unable to use more than 1 scope. Using version 3.0.10
