### ISSUE TITLE
Need to be able to query CompanyProfile Email

### ISSUE THREAD

**Issue by cblackuk** [Microsoft/Partner-Center-PowerShell#23]
We used to be able to query registered emial fro Get-PCCustomer and via
Get-PCCustomerCompanyProfile -TenantId $($CustomerDetails.id) cmdlets.

New commands do not have equivalent of the latter and the Get-PartnerCustomer does not contain that information. It is extremely important we get that email address as we use it for on-boarding throughout the code,

```powershell
Get-PCCustomerCompanyProfile -TenantId $($CustomerDetails.id)

tenantId    : x-x-x-x-xxxxxx
domain      : xxxxxonmicrosoft.com
companyName : Default Directory
address     : @{country=GB}
email       : xxxx@gmail.com
links       : @{self=}
attributes  : @{objectType=CustomerCompanyProfile}
```

Also:
```powershell
$Customer = Get-PCCustomer -TenantId $($CustomerDetails.id)
$Customer.CompanyProfile.Email
x@gmail.com
```

And:
```powershell
$Customer = Get-PCCustomer -TenantId $($CustomerDetails.id)
$Customer
id                    :  x-x-x-x-xxxxx
commerceId            : x-x-x-x-xxxxx
companyProfile        : @{tenantId=x-x-x-x-x; domain=x.onmicrosoft.com; companyName=Default Directory; address=; email=x@gmail.com; links=; attributes=}
billingProfile        : @{id=xxx-xxx-xxx-xxx-xxx ; firstName=xxx-xxx-xxx-974b-xxxx; lastName=xxx-xx-47d8-xx-xx; culture=en-US; language=en; companyName=Default Directory; defaultAddress=; links=; attributes=}
relationshipToPartner : reseller
allowDelegatedAccess  : True
customDomains         : {x.onmicrosoft.com}
links                 : @{self=}
attributes            : @{objectType=Customer}
```
New commands however only show:

```powershell
CustomerId                           Domain                                   Name
----------                           ------                                   ----
xx-xx-xx-xx-xxxx x.onmicrosoft.com Default Directory
```
I know that email is in the billing profile but it is exactly what I want to set as it does not get populated from CompanyProfile automatically when you create new sub. It needs to be added in manually and old code allowed me to do it as it was querying:
"https://api.partnercenter.microsoft.com/v1/customers/{0}/profiles/company" 

Can email field be added please and can we have the new command to query it directly as well?

Not sure if we can just fix it by doing this:

https://github.com/Microsoft/Partner-Center-PowerShell/blob/master/src/PowerShell/Models/Customers/PSCustomer.cs

```C#
        /// <summary>
        /// Addtional operations to be performed when cloning an instance of <see cref="Customer" /> to an instance of <see cref="PSCustomer" />. 
        /// </summary>
        /// <param name="customer">The customer being cloned.</param>
        private void CloneAdditionalOperations(Customer customer)
        {
            CustomerId = customer.Id;
            Domain = customer?.CompanyProfile?.Domain;
            Name = customer?.CompanyProfile?.CompanyName;
            Email =  customer?.CompanyProfile?.Email;
}
```

**Comment by isaiahwilliams** [comment]
HI @cblackuk,

Most of the profile operations, that are scoped to a customer, are not available yet. With the release that we are targeting for later this week will contain the following new features

- Addition of the Get-PartnerCustomerBillingProfile command
- Addition of the Get-PartnerCustomerCompanyProfile commmand 
- All regex patterns will ignore case
- Support for app only authentication

RIght now we are hoping to have these release available by Thursday.

**Comment by isaiahwilliams** [comment]
Hi @cblackuk, 

I just published version [1.5.1810.2](https://www.powershellgallery.com/packages/PartnerCenter/1.5.1810.2) which includes two new command 

- Get-PartnerCustomerBillingProfile 
- Get-PartnerCustomerCompanyProfile

You will be able to get the email address using the billing profile command. Please let me know if you have any issues with this new command.

**Comment by cblackuk** [comment]
Hi @isaiahwilliams 

Thanks for that but sadly that does not fix my issue.

Old command on CompanyProfile would return email as it does it the GUI and this is the only email that gets populated for a brand new domain.

BillingProfile email is what I need to set but I need to query it from CompanyProfile (that is how I did it with old modules and APIs) so can we please add email field to CompanyProfile as it is there in the GUI and API ;-(

**Comment by isaiahwilliams** [comment]
Hi Chris, 

My apologizes I completely missed that those fields where missing from the model. I just got them added, and they will be included in the next release of the module. I will double check the other models to make sure nothing else is missing.

**Comment by cblackuk** [comment]
@isaiahwilliams Thanks is extraordinary :-) Thanks for that! It would be a massive help for me to get it included :)

**Comment by cblackuk** [comment]
> 
> 
> Hi @cblackuk,
> 
> My apologizes I completely missed that those fields where missing from the model. I just got them added, and they will be included in the next release of the module. I will double check the other models to make sure nothing else is missing.

Hi @isaiahwilliams  I can see that you published new module three days ago but those fields are still missing... am I missing something here? ;(

**Comment by cblackuk** [comment]
Hi @isaiahwilliams any update on this please?

**Comment by cblackuk** [comment]
Hi @isaiahwilliams I am trying to aviod raising it again but old cmdlets have now been depricated and I have nothing to replace them with. How can I escalate it please?

**Comment by isaiahwilliams** [comment]
Hi @cblackuk, 

This version of the PowerShell module is using the .NET SDK to request information from the Partner Center API. The address and email properties are not included on the model the SDK is using to deserialize the response from the API. This means the values are going to be omitted. I am actively working on an alternative solution. The hope is to have this solution available next week, but I will not know for sure until I am able to resolve a blocking issue.

**Comment by cblackuk** [comment]
Hi @isaiahwilliams  Thank you ever so much! This would be a life-saver as I need to finish re-writing all the code for the new module and without it I am really stuck...

**Comment by isaiahwilliams** [comment]
Hi @cblackuk, 

The required changes for this to work have been merged. There a handful of features we are still working to add for the next release. If you need a solution ahead of the upcoming release, please feel free to compile the project using Visual Studio and copy the assemblies into the PowerShell module directory.

**Comment by cblackuk** [comment]
Hi @isaiahwilliams,

Thank you very much for an update on this.

Any idea when you will be launching the new release so I can decide based on that please?

**Comment by isaiahwilliams** [comment]
Hi Chris,

The goal is to have this published on Friday of this week. However, there is a possibility this will be delayed because an internal process and the holiday in the US. I will update this issue once it has been published.

Isaiah Williams
________________________________

**Comment by cblackuk** [comment]
Hi @isaiahwilliams,

Thanks for the update, I think we can wait till Friday.

**Comment by isaiahwilliams** [comment]
Hi @cblackuk, 

This issue has been addressed with the release of version [1.5.1811.4](https://www.powershellgallery.com/packages/PartnerCenter/1.5.1811.4). Thank you for working with me to get this issue resolved. Please let us know if you have any other issues.

**Comment by cblackuk** [comment]
Thanks @isaiahwilliams  will test it first thing in the morning :-)
